### ISSUE TITLE
The Java code doesn't not work

### ISSUE THREAD

**Issue by yitbarek123** [walt-id/waltid-ssikit-examples#21]
Hi, I have the following related issues

1, running the java example locally as stated on the readme doesn't work. I used the latest gradle docker image.

2, gradle build fails when I add ```implementation("id.walt:waltid-ssikit:v1.2304101159.0")``` on android studio . Is it possible to use walt-id on android studio with java language?

For, the first case I attached the screenshot 

![Screenshot from 2023-04-16 21-49-19](https://user-images.githubusercontent.com/41948133/232338695-772d22ae-a8a5-487d-889e-8558b73ef90e.png)

Thanks.

**Comment by yitbarek123** [comment]
1,  Yes.
2,  I just checked without 'v' but it doesn't work

![image](https://user-images.githubusercontent.com/41948133/232883458-d3110390-b1e4-4820-9eed-de1f1ba8ee70.png)

**Comment by mikeplotean** [comment]
Ok, so I loaded the project with android studio and I could run the java examples.

I used the latest Flamingo, it comes bundled with JDK17 (the miminum requirement for ssikit being 16). Otherwise, it is also possible to set the JDK from Settings -> Build Tools -> Gradle: Gradle JDK.

If anything higher than 16 is used, it might display smth. similar to this error message: '_Unsupported Java.  Your build is currently configured to use Java 18 and Gradle 7.2._'. In this case, just open `gradle-wrapper.properties` from the _gradle/wrapper_ folder and update the `distributionUrl` to a higher value (e.g. https\://services.gradle.org/distributions/gradle-7.4.1-bin.zip) and reload the project.

**Comment by yitbarek123** [comment]
Thanks @mikeplotean. Now, I'm able to use the jars on android studio after building using jdk17 on terminal. 

But, can you tell me the steps that you followed to run the example on android. For example the app crashes if I try to create a did using

```
DidService.INSTANCE.create(DidMethod.ebsi, null, null);
```
also, variables in the example are declared using type "var" which is creating error for me on android studio.
