### ISSUE TITLE
Failed to transform jackson-core-2.15.2.jar

### ISSUE THREAD

**Issue by mesharkw** [walt-id/waltid-ssikit-examples#28]
Please check this Issue and revert to the previous versions.
https://issuetracker.google.com/issues/297122564

**Comment by cpatsonakis** [comment]
Hello!

Thank you for your report. We have looked in to this and, as it turns out, the code in this repository actually uses v2.15.0 of the jackson-core library (although the v2.15.2 does get pulled as well - but never used). Furthermore, we only use this library in one place just for the JsonIgnore annotation, which is not affected by the issue you referenced.

Thank you again for bringing this to our attention.

Closing this issue for now!
